"""init

Revision ID: 1f6579bd1354
Revises: 
Create Date: 2026-02-14 14:42:10.181639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f6579bd1354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_unionid'), ['unionid'], unique=True)

    op.create_table('word_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('word_civilian', sa.String(length=32), nullable=False),
    sa.Column('word_undercover', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_civilian', 'word_undercover', name='unique_pair')
    )
    with op.batch_alter_table('word_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_pairs_category'), ['category'], unique=False)

    op.create_table('game_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('winner_team', sa.String(length=16), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('undercover_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('civilian_word', sa.String(length=32), nullable=True),
    sa.Column('undercover_word', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_records_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_records_room_id'))

    op.drop_table('game_records')
    with op.batch_alter_table('word_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_pairs_category'))

    op.drop_table('word_pairs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_unionid'))
        batch_op.drop_index(batch_op.f('ix_users_openid'))

    op.drop_table('users')
    # ### end Alembic commands ###
